const GATEWAY_URI = 'wss://gateway.discord.gg/';

const INCOMING_PACKETS = {
    EVENT_DISPATCH: 0x00,
    RECONNECT: 0x07,
    INVALID_SESSION: 0x09,
    READY: 0x0a,
    HEARTBEAT_RECEIVE: 0x0b,
};
const OUTGOING_PACKETS = {
    HEARTBEAT_SEND: 0x01,
    AUTHORIZE: 0x02,
    PRESENCE_UPDATE: 0x03,
    VOICE_STATE_UPDATE: 0x04,
    RESUME_CONNECTION: 0x06,
    GUILD_MEMBERS_REQUEST: 0x08,
};

module.exports = { GATEWAY_URI, INCOMING_PACKETS, OUTGOING_PACKETS };